### ISSUE TITLE
Is it possible to get the account/username associated with keychain Entry?

### ISSUE THREAD

**Issue by ahmed-Q4** [jgilfillan/keyringr#2]
Hello

Thank for a great package... Looking at the code, i was wondering if it is possible to modify the system command to get the account/user associated with the password.

Thanks

**Comment by jgilfillan** [comment]
Glad you like the package.

What would be the benefit of this feature over the existing base R functionality `Sys.getenv("USERNAME")`?

**Comment by ahmed-Q4** [comment]
Currently, this command returns an empty string "". 

I imagine, even it were to work, as intended, it would return the username of the machine i am logged in - similar to "whoami" terminal command.

However, the scenario i would like to address is one where i am logging in to a remote server with a username different than my local machine username.

I was toying with the terminal: "security find-generic-password -gl", and the information i want is returned as the value of "acct" which in turn is a part of the "attribute"

I just not sure how to parse the output of the "security find-generic-password" command, so any help would be appreciated.

Cheers

**Comment by jgilfillan** [comment]
get_kc_account() added to package.  can you install the development version and let me know if that is sufficient please?

**Comment by ahmed-Q4** [comment]
works perfectly....

Thanks a lot!

**Comment by jgilfillan** [comment]
fixed in v 0.4.0 and submitted to cran
