### ISSUE TITLE
Darwin is not TRUE

### ISSUE THREAD

**Issue by pitchers** [jgilfillan/keyringr#3]
Running the following on Windows 7:

>  library("keyringr")
    mypwd <- decrypt_kc_pw("mydb_myuser")
    print(mypwd)

I get the following error:
`Error: Sys.info()["sysname"] == "Darwin" is not TRUE. `

Reference:
[https://stackoverflow.com/a/41435304/7255](https://stackoverflow.com/a/41435304/7255)

**Comment by jgilfillan** [comment]
decrypt_kc_pw() is only for MacOS systems that use the MacOS Keychain. Please review the Vignette for details on how the package can be used on Windows:  https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
